"""The feedback contract as code (``docs/feedback-harmonization.md`` §3 in ``Eifi1/ui-kit``).

Schemas, enums, limits, the PATCH rules, rework bodies, crash filing, erasure and the
attachment URL check — every rule keksdose's backend enforces, as pure functions over
plain values, so kastlan and Kurvenschmiede import them instead of writing them a third
time. The database, the queries (RLS, ``company_id``), auth and the routes stay per app.
"""

from __future__ import annotations

from eifi1_server_kit.feedback.attachments import (
    DEFAULT_ATTACHMENT_URL_POLICY,
    DEFAULT_ATTACHMENT_URL_PREFIX,
    OPAQUE_KEY_PATTERN,
    SHA12_KEY_PATTERN,
    UUID32_SHA12_KEY_PATTERN,
    AttachmentUrlPolicy,
)
from eifi1_server_kit.feedback.body import (
    ATTACHMENT_MARKER,
    BLOCK_RULE_RE,
    REWORK_RULE_RE,
    REWORK_STAMP_FORMAT,
    append_rework,
    appended_text,
    attachment_line,
    body_attachment_urls,
    is_rework_append,
    opens_with_rework_rule,
    rework_count,
    rework_stamp,
    split_body_attachments,
)
from eifi1_server_kit.feedback.context import CONTEXT_KEYS, MAX_CONTEXT_SIZE, context_size, stamp_identity
from eifi1_server_kit.feedback.crash import (
    REFERENCE_LENGTH,
    CrashDecision,
    crash_body,
    crash_context,
    crash_fingerprint,
    crash_reference,
    crash_seen_at,
    crash_title,
    decide_crash,
    fold_crash_context,
    normalise_crash_text,
    truncate,
)
from eifi1_server_kit.feedback.enums import (
    AUTHOR_EDITABLE_STATUSES,
    AWAITING_STATUSES,
    PICKABLE_CATEGORIES,
    REWORKABLE_STATUSES,
    TERMINAL_STATUSES,
    FeedbackCategory,
    FeedbackStatus,
)
from eifi1_server_kit.feedback.erasure import (
    ERASED_MARK,
    FEEDBACK_CONTEXT_KEEP,
    MIN_NEEDLE_LENGTH,
    AnonymisedFeedback,
    anonymise_feedback,
    attachment_keys_to_purge,
    feedback_attachment_urls,
    scrub_context,
    scrub_text,
)
from eifi1_server_kit.feedback.errors import (
    CrashCategoryNotAssignableError,
    FeedbackError,
    FeedbackForbiddenError,
    FeedbackValidationError,
    UnknownAttachmentUrlError,
)
from eifi1_server_kit.feedback.rules import (
    AUTHOR_EDITABLE_FIELDS,
    UpdatePlan,
    check_author_edit,
    plan_update,
    reject_manual_crash,
    reopens,
    resolved_at_change,
)
from eifi1_server_kit.feedback.schemas import (
    MAX_ATTACHMENT_URLS,
    MAX_BODY_LENGTH,
    MAX_SCREENSHOT_URL_LENGTH,
    MAX_TITLE_LENGTH,
    NOT_NULLABLE_FIELDS,
    CrashReportCreate,
    CrashReportResponse,
    FeedbackAttachmentResponse,
    FeedbackCreate,
    FeedbackResponse,
    FeedbackUpdate,
)
from eifi1_server_kit.uploads import ACCEPT_LIST, ACCEPTED_MEDIA_TYPES, MAX_ATTACHMENT_BYTES

__all__ = [
    "ACCEPTED_MEDIA_TYPES",
    "ACCEPT_LIST",
    "ATTACHMENT_MARKER",
    "AUTHOR_EDITABLE_FIELDS",
    "AUTHOR_EDITABLE_STATUSES",
    "AWAITING_STATUSES",
    "BLOCK_RULE_RE",
    "CONTEXT_KEYS",
    "DEFAULT_ATTACHMENT_URL_POLICY",
    "DEFAULT_ATTACHMENT_URL_PREFIX",
    "ERASED_MARK",
    "FEEDBACK_CONTEXT_KEEP",
    "MAX_ATTACHMENT_BYTES",
    "MAX_ATTACHMENT_URLS",
    "MAX_BODY_LENGTH",
    "MAX_CONTEXT_SIZE",
    "MAX_SCREENSHOT_URL_LENGTH",
    "MAX_TITLE_LENGTH",
    "MIN_NEEDLE_LENGTH",
    "NOT_NULLABLE_FIELDS",
    "OPAQUE_KEY_PATTERN",
    "PICKABLE_CATEGORIES",
    "REFERENCE_LENGTH",
    "REWORKABLE_STATUSES",
    "REWORK_RULE_RE",
    "REWORK_STAMP_FORMAT",
    "SHA12_KEY_PATTERN",
    "TERMINAL_STATUSES",
    "UUID32_SHA12_KEY_PATTERN",
    "AnonymisedFeedback",
    "AttachmentUrlPolicy",
    "CrashCategoryNotAssignableError",
    "CrashDecision",
    "CrashReportCreate",
    "CrashReportResponse",
    "FeedbackAttachmentResponse",
    "FeedbackCategory",
    "FeedbackCreate",
    "FeedbackError",
    "FeedbackForbiddenError",
    "FeedbackResponse",
    "FeedbackStatus",
    "FeedbackUpdate",
    "FeedbackValidationError",
    "UnknownAttachmentUrlError",
    "UpdatePlan",
    "anonymise_feedback",
    "append_rework",
    "appended_text",
    "attachment_keys_to_purge",
    "attachment_line",
    "body_attachment_urls",
    "check_author_edit",
    "context_size",
    "crash_body",
    "crash_context",
    "crash_fingerprint",
    "crash_reference",
    "crash_seen_at",
    "crash_title",
    "decide_crash",
    "feedback_attachment_urls",
    "fold_crash_context",
    "is_rework_append",
    "normalise_crash_text",
    "opens_with_rework_rule",
    "plan_update",
    "reject_manual_crash",
    "reopens",
    "resolved_at_change",
    "rework_count",
    "rework_stamp",
    "scrub_context",
    "scrub_text",
    "split_body_attachments",
    "stamp_identity",
    "truncate",
]
