"""Sign-in, sign-up and the account, as code (``docs/auth-harmonization.md`` §8 in ``Eifi1/ui-kit``).

Layer 1, like the rest of the kit: pure functions, Pydantic models and small classes —
no database, no app ``User``, no routes, and no JWT signing (each app keeps its JWT
library; :mod:`~eifi1_server_kit.auth.tokens` builds and checks the claims). keksdose is
the reference, cited ``file`` per rule.

* :mod:`~eifi1_server_kit.auth.accounts` — the address and its tag, invitations, the
  registration gate, names, erasure identifiers;
* :mod:`~eifi1_server_kit.auth.tokens` — one-time tokens (reset, verification,
  invitation, email change) and the session's claims;
* :mod:`~eifi1_server_kit.auth.limits` — :class:`AuthLimiters`, with the per-address
  delay that never locks out;
* :mod:`~eifi1_server_kit.auth.schemas` — the wire shapes;
* :mod:`~eifi1_server_kit.auth.errors` — :class:`AuthError` and its codes.
"""

from __future__ import annotations

from eifi1_server_kit.auth.accounts import (
    FAMILY_NAME_FIRST,
    FAMILY_NAME_FIRST_NO_SPACE,
    TAG_SEPARATOR,
    RegistrationDecision,
    addresses_for_reset,
    env_list_match,
    erasure_identifiers,
    full_name,
    invitation_accepts,
    name_incomplete,
    normalise_email,
    parse_env_list,
    registration_decision,
    tagged_variant,
    verified_by_invitation,
)
from eifi1_server_kit.auth.errors import AUTH_ERROR_DETAIL, AUTH_ERROR_STATUS, AuthError, AuthErrorCode
from eifi1_server_kit.auth.limits import (
    CHALLENGE_PER_IP,
    CHALLENGE_PER_SUBJECT,
    LOGIN_FAILURE_BASE_DELAY,
    LOGIN_FAILURE_MAX_DELAY,
    LOGIN_FAILURE_WINDOW_SECONDS,
    LOGIN_FAILURES_FREE,
    LOGIN_PER_IP,
    REGISTER_PER_IP,
    RESET_PER_ADDRESS,
    RESET_PER_IP,
    VERIFICATION_RESEND_PER_RECIPIENT,
    AuthLimiters,
    Budget,
    LoginFailureThrottle,
    login_failure_delay,
)
from eifi1_server_kit.auth.schemas import (
    DEFAULT_LOCALE,
    LOCALE_PATTERN,
    MAX_EMAIL_LENGTH,
    MAX_NAME_LENGTH,
    MAX_PASSWORD_BYTES,
    MIN_PASSWORD_LENGTH,
    PROFILE_NOT_NULLABLE,
    Email,
    ExistingPassword,
    LocaleTag,
    LoginRequest,
    NewPassword,
    PasswordChangeChallenge,
    PersonName,
    ProfileUpdate,
    RegisterRequest,
    TokenResponse,
    TwoFactorChallenge,
    UserResponse,
)
from eifi1_server_kit.auth.tokens import (
    ACCESS_TOKEN_EXPIRE_MINUTES,
    ACCESS_TOKEN_LIFETIME,
    ACCESS_TOKEN_TYPE,
    CHALLENGE_LIFETIMES,
    EMAIL_CHANGE_TOKEN_KIND,
    EMAIL_CHANGE_TTL,
    INVITE_TTL,
    ONE_TIME_TOKEN_BYTES,
    ONE_TIME_TOKEN_TTLS,
    PROFILE_CLAIMS,
    REFRESH_TOKEN_EXPIRE_MINUTES,
    REFRESH_TOKEN_LIFETIME,
    REFRESH_TOKEN_TYPE,
    RESERVED_CLAIMS,
    RESET_TTL,
    VERIFY_TTL,
    ChallengeKind,
    MintedToken,
    OneTimeTokenKind,
    access_claims,
    challenge_claims,
    hash_token,
    is_expired,
    mint,
    refresh_claims,
    token_is_revoked,
)

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "ACCESS_TOKEN_LIFETIME",
    "ACCESS_TOKEN_TYPE",
    "AUTH_ERROR_DETAIL",
    "AUTH_ERROR_STATUS",
    "CHALLENGE_LIFETIMES",
    "CHALLENGE_PER_IP",
    "CHALLENGE_PER_SUBJECT",
    "DEFAULT_LOCALE",
    "EMAIL_CHANGE_TOKEN_KIND",
    "EMAIL_CHANGE_TTL",
    "FAMILY_NAME_FIRST",
    "FAMILY_NAME_FIRST_NO_SPACE",
    "INVITE_TTL",
    "LOCALE_PATTERN",
    "LOGIN_FAILURES_FREE",
    "LOGIN_FAILURE_BASE_DELAY",
    "LOGIN_FAILURE_MAX_DELAY",
    "LOGIN_FAILURE_WINDOW_SECONDS",
    "LOGIN_PER_IP",
    "MAX_EMAIL_LENGTH",
    "MAX_NAME_LENGTH",
    "MAX_PASSWORD_BYTES",
    "MIN_PASSWORD_LENGTH",
    "ONE_TIME_TOKEN_BYTES",
    "ONE_TIME_TOKEN_TTLS",
    "PROFILE_CLAIMS",
    "PROFILE_NOT_NULLABLE",
    "REFRESH_TOKEN_EXPIRE_MINUTES",
    "REFRESH_TOKEN_LIFETIME",
    "REFRESH_TOKEN_TYPE",
    "REGISTER_PER_IP",
    "RESERVED_CLAIMS",
    "RESET_PER_ADDRESS",
    "RESET_PER_IP",
    "RESET_TTL",
    "TAG_SEPARATOR",
    "VERIFICATION_RESEND_PER_RECIPIENT",
    "VERIFY_TTL",
    "AuthError",
    "AuthErrorCode",
    "AuthLimiters",
    "Budget",
    "ChallengeKind",
    "Email",
    "ExistingPassword",
    "LocaleTag",
    "LoginFailureThrottle",
    "LoginRequest",
    "MintedToken",
    "NewPassword",
    "OneTimeTokenKind",
    "PasswordChangeChallenge",
    "PersonName",
    "ProfileUpdate",
    "RegisterRequest",
    "RegistrationDecision",
    "TokenResponse",
    "TwoFactorChallenge",
    "UserResponse",
    "access_claims",
    "addresses_for_reset",
    "challenge_claims",
    "env_list_match",
    "erasure_identifiers",
    "full_name",
    "hash_token",
    "invitation_accepts",
    "is_expired",
    "login_failure_delay",
    "mint",
    "name_incomplete",
    "normalise_email",
    "parse_env_list",
    "refresh_claims",
    "registration_decision",
    "tagged_variant",
    "token_is_revoked",
    "verified_by_invitation",
]
